// Midway recipes are manually added post PCWJ to make recipes more sensible and
// introduce new steps to the existing, converted recipes. They're in a separate
// place for now because the converted recipes are autogenerated and we don't
// want them to be overwritten.

/datum/cooking/recipe/torilla
	container_type = /obj/item/reagent_containers/cooking/pan
	product_type = /obj/item/food/tortilla
	catalog_category = COOKBOOK_CATEGORY_BREAD
	steps = list(
		PCWJ_ADD_ITEM(/obj/item/food/sliced/dough),
		PCWJ_USE_STOVE(J_LO, 10 SECONDS),
	)

/datum/cooking/recipe/cooked_patty
	container_type = /obj/item/reagent_containers/cooking/grill_grate
	product_type = /obj/item/food/meat/patty
	catalog_category = COOKBOOK_CATEGORY_MEAT
	steps = list(
		PCWJ_ADD_ITEM(/obj/item/food/meat/patty_raw),
		PCWJ_ADD_REAGENT("sodiumchloride", 1, optional = TRUE),
		PCWJ_USE_GRILL(J_LO, 10 SECONDS),
	)

/datum/cooking/recipe/cooked_meatball
	container_type = /obj/item/reagent_containers/cooking/grill_grate
	product_type = /obj/item/food/meatball
	catalog_category = COOKBOOK_CATEGORY_MEAT
	steps = list(
		PCWJ_ADD_ITEM(/obj/item/food/meat/raw_meatball),
		PCWJ_ADD_REAGENT("sodiumchloride", 1, optional = TRUE),
		PCWJ_USE_GRILL(J_LO, 10 SECONDS),
	)

/datum/cooking/recipe/taco
	container_type = /obj/item/reagent_containers/cooking/board
	product_type = /obj/item/food/taco
	catalog_category = COOKBOOK_CATEGORY_MEAT
	steps = list(
		PCWJ_ADD_ITEM(/obj/item/food/tortilla),
		PCWJ_ADD_ITEM(/obj/item/food/cutlet),
		PCWJ_ADD_ITEM(/obj/item/food/sliced/cheesewedge),
	)

/datum/cooking/recipe_step/add_item/fried_vox

/datum/cooking/recipe_step/add_item/fried_vox/check_conditions_met(obj/added_item, datum/cooking/recipe_tracker/tracker)
	var/obj/item/organ/external/external = added_item
	if(!istype(external))
		return PCWJ_CHECK_INVALID

	if(istype(external.dna.species, /datum/species/vox))
		return PCWJ_CHECK_VALID

	return PCWJ_CHECK_INVALID

/datum/cooking/recipe/kfv
	container_type = /obj/item/reagent_containers/cooking/deep_basket
	product_type = /obj/item/food/fried_vox
	steps = list(
		new /datum/cooking/recipe_step/add_item/fried_vox(),
		PCWJ_USE_DEEP_FRYER(10 SECONDS),
	)
	appear_in_default_catalog = FALSE

/datum/cooking/recipe_step/add_item/deep_fried_anything

/datum/cooking/recipe_step/add_item/deep_fried_anything/check_conditions_met(obj/added_item, datum/cooking/recipe_tracker/tracker)
	var/obj/item/food/food_item = added_item
	if(!istype(food_item))
		return PCWJ_CHECK_INVALID

	if("deep fried" in food_item.cooktype)
		tracker.step_reaction_message = "That is already deep-fried!"
		return PCWJ_CHECK_INVALID

	// check to see if this is something that belongs to another deep fryer
	// recipe with only one item
	for(var/datum/cooking/recipe/recipe in GLOB.pcwj_recipe_dictionary[/obj/item/reagent_containers/cooking/deep_basket])
		if(length(recipe.steps) == 2) // One add step and one deep fry step
			var/datum/cooking/recipe_step/add_item/add_item_step = recipe.steps[1]
			if(istype(add_item_step) && (src != add_item_step) && add_item_step.check_conditions_met(added_item, tracker) == PCWJ_CHECK_VALID)
				return PCWJ_CHECK_INVALID

	return PCWJ_CHECK_VALID

/datum/cooking/recipe/deep_fried_anything
	container_type = /obj/item/reagent_containers/cooking/deep_basket
	steps = list(
		new /datum/cooking/recipe_step/add_item/deep_fried_anything(),
		PCWJ_USE_DEEP_FRYER(10 SECONDS),
	)
	appear_in_default_catalog = FALSE

/datum/cooking/recipe/deep_fried_anything/create_product(datum/cooking/recipe_tracker/tracker)
	var/obj/item/reagent_containers/cooking/container = locateUID(tracker.container_uid)
	if(!istype(container))
		stack_trace("couldn't find container for deep fried everything recipe")

	var/obj/item/food/food_item = container.contents[1]
	var/obj/item/food/result = new(container)
	result.icon = food_item.icon
	result.icon_state = food_item.icon_state
	result.color = "#FFAD33"
	result.name = "deep-fried [food_item.name]"
	result.desc = "It has been deep-fried."
	result.cooktype["deep fried"] = TRUE
	food_item.reagents.trans_to(result, food_item.reagents.total_volume)
	qdel(food_item)

/datum/cooking/recipe/jellybean_red
	container_type = /obj/item/reagent_containers/cooking/mould/bean
	product_type = /obj/item/food/candy/jellybean/red
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("cherryjelly", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/jellybean_blue
	container_type = /obj/item/reagent_containers/cooking/mould/bean
	product_type = /obj/item/food/candy/jellybean/blue
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("berryjuice", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/jellybean_poison
	container_type = /obj/item/reagent_containers/cooking/mould/bean
	product_type = /obj/item/food/candy/jellybean/poison
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("poisonberryjuice", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/jellybean_green
	container_type = /obj/item/reagent_containers/cooking/mould/bean
	product_type = /obj/item/food/candy/jellybean/green
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("limejuice", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/jellybean_yellow
	container_type = /obj/item/reagent_containers/cooking/mould/bean
	product_type = /obj/item/food/candy/jellybean/yellow
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("lemonjuice", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/jellybean_orange
	container_type = /obj/item/reagent_containers/cooking/mould/bean
	product_type = /obj/item/food/candy/jellybean/orange
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("orangejuice", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/gummybear_blue
	container_type = /obj/item/reagent_containers/cooking/mould/bear
	product_type = /obj/item/food/candy/gummybear/blue
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("berryjuice", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/gummybear_green
	container_type = /obj/item/reagent_containers/cooking/mould/bear
	product_type = /obj/item/food/candy/gummybear/green
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("limejuice", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/gummybear_orange
	container_type = /obj/item/reagent_containers/cooking/mould/bear
	product_type = /obj/item/food/candy/gummybear/orange
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("orangejuice", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/gummybear_poison
	container_type = /obj/item/reagent_containers/cooking/mould/bear
	product_type = /obj/item/food/candy/gummybear/poison
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("poisonberryjuice", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/gummybear_purple
	container_type = /obj/item/reagent_containers/cooking/mould/bear
	product_type = /obj/item/food/candy/gummybear/purple
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("grapejuice", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/gummybear_red
	container_type = /obj/item/reagent_containers/cooking/mould/bear
	product_type = /obj/item/food/candy/gummybear/red
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("cherryjelly", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/gummybear_wtf
	container_type = /obj/item/reagent_containers/cooking/mould/bear
	product_type = /obj/item/food/candy/gummybear/wtf
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("space_drugs", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/gummybear_wtf2
	container_type = /obj/item/reagent_containers/cooking/mould/bear
	product_type = /obj/item/food/candy/gummybear/wtf
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_PRODUCE(/obj/item/food/grown/ambrosia/vulgaris),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/gummybear_yellow
	container_type = /obj/item/reagent_containers/cooking/mould/bear
	product_type = /obj/item/food/candy/gummybear/yellow
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("lemonjuice", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/gummyworm_blue
	container_type = /obj/item/reagent_containers/cooking/mould/worm
	product_type = /obj/item/food/candy/gummyworm/blue
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("berryjuice", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/gummyworm_green
	container_type = /obj/item/reagent_containers/cooking/mould/worm
	product_type = /obj/item/food/candy/gummyworm/green
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("limejuice", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/gummyworm_orange
	container_type = /obj/item/reagent_containers/cooking/mould/worm
	product_type = /obj/item/food/candy/gummyworm/orange
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("orangejuice", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/gummyworm_poison
	container_type = /obj/item/reagent_containers/cooking/mould/worm
	product_type = /obj/item/food/candy/gummyworm/poison
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("poisonberryjuice", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/gummyworm_purple
	container_type = /obj/item/reagent_containers/cooking/mould/worm
	product_type = /obj/item/food/candy/gummyworm/purple
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("grapejuice", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/gummyworm_red
	container_type = /obj/item/reagent_containers/cooking/mould/worm
	product_type = /obj/item/food/candy/gummyworm/red
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("cherryjelly", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/gummyworm_wtf
	container_type = /obj/item/reagent_containers/cooking/mould/worm
	product_type = /obj/item/food/candy/gummyworm/wtf
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("space_drugs", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/gummyworm_wtf2
	container_type = /obj/item/reagent_containers/cooking/mould/worm
	product_type = /obj/item/food/candy/gummyworm/wtf
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_PRODUCE(/obj/item/food/grown/ambrosia/vulgaris),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/gummyworm_yellow
	container_type = /obj/item/reagent_containers/cooking/mould/worm
	product_type = /obj/item/food/candy/gummyworm/yellow
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("lemonjuice", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/jellybean_chocolate
	container_type = /obj/item/reagent_containers/cooking/mould/bean
	product_type = /obj/item/food/candy/jellybean/chocolate
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_ITEM(/obj/item/food/chocolatebar),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/jellybean_coffee
	container_type = /obj/item/reagent_containers/cooking/mould/bean
	product_type = /obj/item/food/candy/jellybean/coffee
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("coffee", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/jellybean_cola
	container_type = /obj/item/reagent_containers/cooking/mould/bean
	product_type = /obj/item/food/candy/jellybean/cola
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("cola", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/jellybean_drgibb
	container_type = /obj/item/reagent_containers/cooking/mould/bean
	product_type = /obj/item/food/candy/jellybean/drgibb
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("dr_gibb", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/jellybean_popcorn
	container_type = /obj/item/reagent_containers/cooking/mould/bean
	product_type = /obj/item/food/candy/jellybean/popcorn
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_ITEM(/obj/item/food/popcorn),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/jellybean_purple
	container_type = /obj/item/reagent_containers/cooking/mould/bean
	product_type = /obj/item/food/candy/jellybean/purple
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("grapejuice", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/jellybean_wtf
	container_type = /obj/item/reagent_containers/cooking/mould/bean
	product_type = /obj/item/food/candy/jellybean/wtf
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_REAGENT("space_drugs", 5),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)

/datum/cooking/recipe/jellybean_wtf2
	container_type = /obj/item/reagent_containers/cooking/mould/bean
	product_type = /obj/item/food/candy/jellybean/wtf
	catalog_category = COOKBOOK_CATEGORY_CANDY
	steps = list(
		PCWJ_ADD_REAGENT("sugar", 5),
		PCWJ_ADD_REAGENT("water", 5),
		PCWJ_ADD_REAGENT("cornoil", 5),
		PCWJ_ADD_PRODUCE(/obj/item/food/grown/ambrosia/vulgaris),
		PCWJ_USE_ICE_CREAM_MIXER(10 SECONDS),
	)
