/datum/game_test/room_test/attack_chain_borgs/Run()
	var/datum/test_puppeteer/player = new(src)
	player.puppet.name = "Player"

	var/mob/living/silicon/robot/borg = player.spawn_mob_nearby(/mob/living/silicon/robot)
	borg.name = "BORGO"

	player.set_intent(INTENT_HARM)
	player.click_on(borg)
	TEST_ASSERT_LAST_CHATLOG(player, "but doesn't leave a dent")

	player.set_intent(INTENT_HELP)
	player.spawn_obj_in_hand(/obj/item/card/id/roboticist)
	player.click_on(borg)
	TEST_ASSERT_LAST_CHATLOG(player, "You unlock BORGO's interface")
	player.puppet.swap_hand()
	var/obj/item/crowbar = player.spawn_obj_in_hand(/obj/item/crowbar)
	crowbar.attack_verb = list("bashed")
	player.click_on(borg)
	TEST_ASSERT_LAST_CHATLOG(player, "You open the cover")
	player.put_away(crowbar)
	player.click_on(borg)
	TEST_ASSERT_LAST_CHATLOG(player, "You remove the high-capacity power cell")
	player.click_on(borg)
	TEST_ASSERT_LAST_CHATLOG(player, "You insert the power cell")
	player.retrieve(crowbar)
	player.click_on(borg)
	TEST_ASSERT_LAST_CHATLOG(player, "You close the cover")
	player.puppet.swap_hand()
	player.click_on(borg)
	TEST_ASSERT_LAST_CHATLOG(player, "You lock BORGO's interface")
	player.puppet.swap_hand()
	player.set_intent(INTENT_HARM)
	player.click_on(borg)
	TEST_ASSERT_LAST_CHATLOG(player, "Player has bashed BORGO with the crowbar")
	TEST_ASSERT(borg.health <= borg.maxHealth, "borg did not take damage")
