"TGUI":
- 'tgui/**'

"Звук":
- '**/*.ogg'

"Изменение Карты":
- '**/*.dmm'

"Инструменты":
- '.gihub/workflows/**'
- 'tools/**'

"Керберос":
- '_maps/map_files220/delta/delta.dmm'

"Кибериада":
- '_maps/map_files220/cyberiad/cyberiad.dmm'

"Цереброн":
- '_maps/map_files220/MetaStation/MetaStation.dmm'

"НЕ МОДУЛЬНО":
- all: ['code/**']

"Спрайты":
- '**/*.dmi'

"Требуется изменение конфига":
- 'config/**'

"Документация":
- '**/*.md'

"Частичная модульность":
- all: ['code/**', modular_ss220/**]

"SQL":
- 'SQL/**'
