#undef SOUND_EFFECT_NONE
#undef SOUND_EFFECT_RADIO
#undef SOUND_EFFECT_ROBOT
#undef SOUND_EFFECT_RADIO_ROBOT
#undef SOUND_EFFECT_MEGAPHONE
#undef SOUND_EFFECT_MEGAPHONE_ROBOT

#undef CHANNEL_TTS_RADIO

#undef TTS_TRAIT_PITCH_WHISPER
#undef TTS_TRAIT_RATE_FASTER
#undef TTS_TRAIT_RATE_MEDIUM

#undef TTS_CATEGORY_OTHER
#undef TTS_CATEGORY_WARCRAFT3
#undef TTS_CATEGORY_HALFLIFE2
#undef TTS_CATEGORY_STARCRAFT
#undef TTS_CATEGORY_PORTAL2
#undef TTS_CATEGORY_STALKER
#undef TTS_CATEGORY_DOTA2
#undef TTS_CATEGORY_LOL
#undef TTS_CATEGORY_FALLOUT
#undef TTS_CATEGORY_FALLOUT2
#undef TTS_CATEGORY_POSTAL2
#undef TTS_CATEGORY_TEAMFORTRESS2
#undef TTS_CATEGORY_ATOMIC_HEART
#undef TTS_CATEGORY_OVERWATCH
#undef TTS_CATEGORY_SKYRIM
#undef TTS_CATEGORY_RITA
#undef TTS_CATEGORY_METRO
#undef TTS_CATEGORY_HEROESOFTHESTORM
#undef TTS_CATEGORY_HEARTHSTONE
#undef TTS_CATEGORY_VALORANT
#undef TTS_CATEGORY_EVILISLANDS

#undef TTS_GENDER_ANY
#undef TTS_GENDER_MALE
#undef TTS_GENDER_FEMALE

#undef TTS_PHRASES

#undef COMSIG_ATOM_TTS_SEED_CHANGE
#undef COMSIG_ATOM_TTS_CAST
#undef COMSIG_ATOM_PRE_TTS_CAST
	#undef COMPONENT_TTS_INTERRUPT
#undef COMSIG_ATOM_TTS_TRAIT_ADD
#undef COMSIG_ATOM_TTS_TRAIT_REMOVE
