services:
  dependencies:
    build:
      dockerfile: Dockerfile.dependencies
    volumes:
      - server-volume
  tgui-builder:
    build:
      dockerfile: Dockerfile.tgui
    volumes:
      - server-volume
  od:
    build:
      dockerfile: Dockerfile.od
    volumes:
      - server-volume
  server:
    build:
      dockerfile: Dockerfile.server
    depends_on:
      - tgui-builder
      - dependencies
      - od
    ports:
      - "5000:5000"
    command: ./tools/ci/run_server.sh
    volumes:
      - server-volume

volumes:
  server-volume:
    driver: local
    driver_opts:
      type: none
      device: /Users/andrew/stuff/server/Paradise
      o: bind
