services:
  byond:
    build:
      dockerfile: Dockerfile.byond
    volumes:
      - server:/server
  tgui:
    build:
      dockerfile: Dockerfile.tgui
    volumes:
      - server:/server
  dme:
    build:
      dockerfile: Dockerfile.dme
    volumes:
      - server:/server
    depends_on:
      - byond
  server:
    build:
      dockerfile: Dockerfile.server
    depends_on:
      # - tgui
      - byond
      - dme
    ports:
      - "8975:8975"
    command: sleep 100000
    # command: DreamDaemon paradise.dmb -close -trusted -verbose
    volumes:
      - server:/server

volumes:
  server:
    driver: local
    driver_opts:
      type: none
      device: /Users/andrew/stuff/server/Paradise/tmp/server
      o: bind
