version: '3.8'

services:
  base-dependencies:
    build:
      context: .
      dockerfile: Dockerfile.base

  tgui-builder:
    build:
      context: .
      dockerfile: Dockerfile.tgui
    volumes:
      - server-volume:/server
    command: ["./tgui/bin/tgui"]

  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - server-volume:/server
    command: ["./tools/ci/run_server.sh"]

volumes:
  server-volume:
