version: '3.8'

services:
  dependencies:
    build:
      context: .
      dockerfile: Dockerfile.dependencies

  tgui-builder:
    build:
      context: .
      dockerfile: Dockerfile.tgui
    volumes:
      - server-volume:/server

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      - tgui-builder
      - dependencies
      - od
    volumes:
      - server-volume:/server

  od:
    build:
      context: .
      dockerfile: Dockerfile.od
    volumes:
      - server-volume:/server

volumes:
  server-volume:
