# This config file exists for you to place overrides in if you are doing a testmerge that has config changes.
# It is in this folder as the entire /config/ dir is a static managed by TGS, so /config/example/ wont work.
# This will not help you for SQL changes.

# Code reviewers, if anything is in this file while you are reviewing before merge, it **NEEDS** binning.

# Anything in here still needs the section header as per regular config.
# Example below:

#[general_configuration]
#lobby_time = 99999999

[event_configuration]
event_delay_lower_bounds = {mundane = 3, moderate = 5, major = 8, disaster = 7}
event_delay_upper_bounds = {mundane = 5.5, moderate = 10, major = 15, disaster = 10}
expected_round_length = 90
event_initial_delays = [
  #{severity = "mundane", lower_bound = 7, upper_bound = 12},
  {severity = "moderate", lower_bound = 15, upper_bound = 19},
  {severity = "major", lower_bound = 25, upper_bound = 32},
  {severity = "disaster", lower_bound = 32, upper_bound = 42},
]

[voting_configuration]
autotransfer_initial_time = 54000
