/mob/living/silicon/robot/Login()
	..()
	regenerate_icons()
	show_laws(0)
	if(connected_ai)
		if(connected_ai.mind.special_role == SPECIAL_ROLE_TRAITOR && connected_ai.malf_picker)
			make_malf_robot()
