/obj/machinery/economy/vending/hatdispenser
	name = "\improper Hatlord 9000"
	desc = "It doesn't seem the slightest bit unusual. This frustrates you immensely."
	icon_state = "hats"
	icon_lightmask = "hats"
	icon_panel = "syndi"
	icon_broken = "wide_vendor"
	category = VENDOR_TYPE_CLOTHING
	ads_list = list(
		"Warning, not all hats are dog/monkey compatible. Apply forcefully with care.",
		"Apply directly to the forehead.",
		"Who doesn't love spending cash on hats?!",
		"From the people that brought you collectable hat crates, Hatlord!",
	)

	products = list(
		/obj/item/clothing/head/that = 2,
		/obj/item/clothing/head/bowlerhat = 10,
		/obj/item/clothing/head/beaverhat = 10,
		/obj/item/clothing/head/boaterhat = 10,
		/obj/item/clothing/head/fedora = 10,
		/obj/item/clothing/head/cowboyhat = 10,
		/obj/item/clothing/head/cowboyhat/black = 10,
		/obj/item/clothing/head/fez = 10,
		/obj/item/clothing/head/soft/solgov = 10,
		/obj/item/clothing/head/beret = 10,
		/obj/item/clothing/head/beret/black = 10,
		/obj/item/clothing/head/headscarf = 10,
		/obj/item/clothing/head/hairflower = 10,
		/obj/item/clothing/head/mailman = 1,
		/obj/item/clothing/head/soft/rainbow = 1,
	)

	contraband = list(/obj/item/clothing/head/bearpelt = 5)

	prices = list(
		/obj/item/clothing/head/that = 30,
		/obj/item/clothing/head/bowlerhat = 20,
		/obj/item/clothing/head/beaverhat = 20,
		/obj/item/clothing/head/boaterhat = 20,
		/obj/item/clothing/head/fedora = 20,
		/obj/item/clothing/head/cowboyhat = 20,
		/obj/item/clothing/head/cowboyhat/black = 20,
		/obj/item/clothing/head/fez = 20,
		/obj/item/clothing/head/soft/solgov = 20,
		/obj/item/clothing/head/beret = 20,
		/obj/item/clothing/head/beret/black = 20,
		/obj/item/clothing/head/headscarf = 20,
		/obj/item/clothing/head/hairflower = 20,
		/obj/item/clothing/head/mailman = 60,
		/obj/item/clothing/head/soft/rainbow = 40,
		/obj/item/clothing/head/bearpelt = 30,
	)

	refill_canister = /obj/item/vending_refill/hatdispenser

/obj/machinery/economy/vending/hatdispenser/free
	prices = list()

/obj/machinery/economy/vending/suitdispenser
	name = "\improper Suitlord 9000"
	desc = "You wonder for a moment why all of your shirts and pants come conjoined. This hurts your head and you stop thinking about it."
	icon_state = "suits"
	icon_lightmask = "suits"
	icon_panel = "syndi"
	icon_broken = "wide_vendor"
	category = VENDOR_TYPE_CLOTHING
	ads_list = list(
		"Pre-Ironed, Pre-Washed, Pre-Wor-*BZZT*",
		"Blood of your enemies washes right out!",
		"Who are YOU wearing?",
		"Look dapper! Look like an idiot!",
		"Dont carry your size? How about you shave off some pounds you fat lazy- *BZZT*",
	)

	products = list(
		/obj/item/clothing/under/color/black = 10,
		/obj/item/clothing/under/color/grey = 10,
		/obj/item/clothing/under/color/white = 10,
		/obj/item/clothing/under/color/darkred = 10,
		/obj/item/clothing/under/color/red = 10,
		/obj/item/clothing/under/color/lightred = 10,
		/obj/item/clothing/under/color/brown = 10,
		/obj/item/clothing/under/color/orange = 10,
		/obj/item/clothing/under/color/lightbrown = 10,
		/obj/item/clothing/under/color/yellow = 10,
		/obj/item/clothing/under/color/yellowgreen = 10,
		/obj/item/clothing/under/color/lightgreen = 10,
		/obj/item/clothing/under/color/green = 10,
		/obj/item/clothing/under/color/aqua = 10,
		/obj/item/clothing/under/color/darkblue = 10,
		/obj/item/clothing/under/color/blue = 10,
		/obj/item/clothing/under/color/lightblue = 10,
		/obj/item/clothing/under/color/purple = 10,
		/obj/item/clothing/under/color/lightpurple = 10,
		/obj/item/clothing/under/color/pink = 10,
		/obj/item/clothing/under/dress/blackskirt = 10,
		/obj/item/clothing/under/color/jumpskirt/black = 10,
		/obj/item/clothing/under/color/jumpskirt/grey = 10,
		/obj/item/clothing/under/color/jumpskirt/white = 10,
		/obj/item/clothing/under/color/jumpskirt/darkred = 10,
		/obj/item/clothing/under/color/jumpskirt/red = 10,
		/obj/item/clothing/under/color/jumpskirt/lightred = 10,
		/obj/item/clothing/under/color/jumpskirt/brown = 10,
		/obj/item/clothing/under/color/jumpskirt/orange = 10,
		/obj/item/clothing/under/color/jumpskirt/lightbrown = 10,
		/obj/item/clothing/under/color/jumpskirt/yellow = 10,
		/obj/item/clothing/under/color/jumpskirt/yellowgreen = 10,
		/obj/item/clothing/under/color/jumpskirt/lightgreen = 10,
		/obj/item/clothing/under/color/jumpskirt/green = 10,
		/obj/item/clothing/under/color/jumpskirt/aqua = 10,
		/obj/item/clothing/under/color/jumpskirt/darkblue = 10,
		/obj/item/clothing/under/color/jumpskirt/blue = 10,
		/obj/item/clothing/under/color/jumpskirt/lightblue = 10,
		/obj/item/clothing/under/color/jumpskirt/purple = 10,
		/obj/item/clothing/under/color/jumpskirt/lightpurple = 10,
		/obj/item/clothing/under/color/jumpskirt/pink = 10,
		/obj/item/clothing/under/color/jumpskirt/rainbow = 1,
		/obj/item/clothing/under/color/rainbow = 1,
	)

	contraband = list(
		/obj/item/clothing/under/syndicate/tacticool = 5,
		/obj/item/clothing/under/syndicate/greyman = 5,
		/obj/item/clothing/under/color/orange/prison = 10,
		/obj/item/clothing/under/color/jumpskirt/orange/prison = 10,
	)

	prices = list(
		/obj/item/clothing/under/color/black = 30,
		/obj/item/clothing/under/dress/blackskirt = 30,
		/obj/item/clothing/under/color/grey = 30,
		/obj/item/clothing/under/color/white = 50,
		/obj/item/clothing/under/color/darkred = 50,
		/obj/item/clothing/under/color/red = 50,
		/obj/item/clothing/under/color/lightred = 50,
		/obj/item/clothing/under/color/brown = 30,
		/obj/item/clothing/under/color/orange = 50,
		/obj/item/clothing/under/color/lightbrown = 30,
		/obj/item/clothing/under/color/yellow = 50,
		/obj/item/clothing/under/color/yellowgreen = 50,
		/obj/item/clothing/under/color/lightgreen = 50,
		/obj/item/clothing/under/color/green = 50,
		/obj/item/clothing/under/color/aqua = 50,
		/obj/item/clothing/under/color/darkblue = 50,
		/obj/item/clothing/under/color/blue = 50,
		/obj/item/clothing/under/color/lightblue = 30,
		/obj/item/clothing/under/color/purple = 50,
		/obj/item/clothing/under/color/lightpurple = 50,
		/obj/item/clothing/under/color/pink = 50,
		/obj/item/clothing/under/color/rainbow = 100,
		/obj/item/clothing/under/color/jumpskirt/black = 30,
		/obj/item/clothing/under/color/jumpskirt/grey = 30,
		/obj/item/clothing/under/color/jumpskirt/white = 50,
		/obj/item/clothing/under/color/jumpskirt/darkred = 50,
		/obj/item/clothing/under/color/jumpskirt/red = 50,
		/obj/item/clothing/under/color/jumpskirt/lightred = 50,
		/obj/item/clothing/under/color/jumpskirt/brown = 30,
		/obj/item/clothing/under/color/jumpskirt/orange = 50,
		/obj/item/clothing/under/color/jumpskirt/lightbrown = 30,
		/obj/item/clothing/under/color/jumpskirt/yellow = 50,
		/obj/item/clothing/under/color/jumpskirt/yellowgreen = 50,
		/obj/item/clothing/under/color/jumpskirt/lightgreen = 50,
		/obj/item/clothing/under/color/jumpskirt/green = 50,
		/obj/item/clothing/under/color/jumpskirt/aqua = 50,
		/obj/item/clothing/under/color/jumpskirt/darkblue = 50,
		/obj/item/clothing/under/color/jumpskirt/blue = 50,
		/obj/item/clothing/under/color/jumpskirt/lightblue = 30,
		/obj/item/clothing/under/color/jumpskirt/purple = 50,
		/obj/item/clothing/under/color/jumpskirt/lightpurple = 50,
		/obj/item/clothing/under/color/jumpskirt/pink = 50,
		/obj/item/clothing/under/color/jumpskirt/rainbow = 100,
		/obj/item/clothing/under/syndicate/tacticool = 75,
		/obj/item/clothing/under/syndicate/greyman = 75,
		/obj/item/clothing/under/color/jumpskirt/orange/prison = 75,
		/obj/item/clothing/under/color/orange/prison = 75,
	)

	refill_canister = /obj/item/vending_refill/suitdispenser

/obj/machinery/economy/vending/suitdispenser/free
	prices = list()

/obj/machinery/economy/vending/shoedispenser
	name = "\improper Shoelord 9000"
	desc = "Wow, hatlord looked fancy, suitlord looked streamlined, and this is just normal. The guy who designed these must be an idiot."
	icon_state = "shoes"
	icon_lightmask = "shoes"
	icon_panel = "syndi"
	icon_broken = "wide_vendor"
	category = VENDOR_TYPE_CLOTHING
	ads_list = list(
		"Put your foot down!",
		"One size fits all!",
		"IM WALKING ON SUNSHINE!",
		"No hobbits allowed.",
		"NO PLEASE WILLY, DONT HURT ME- *BZZT*",
	)

	products = list(
		/obj/item/clothing/shoes/black = 10,
		/obj/item/clothing/shoes/brown = 10,
		/obj/item/clothing/shoes/blue = 10,
		/obj/item/clothing/shoes/green = 10,
		/obj/item/clothing/shoes/yellow = 10,
		/obj/item/clothing/shoes/purple = 10,
		/obj/item/clothing/shoes/red = 10,
		/obj/item/clothing/shoes/white = 10,
		/obj/item/clothing/shoes/laceup = 10,
		/obj/item/clothing/shoes/sandal = 10,
		/obj/item/clothing/shoes/jackboots = 10,
		/obj/item/clothing/shoes/winterboots = 10,
		/obj/item/clothing/shoes/cowboy = 10,
		/obj/item/clothing/shoes/cowboy/black = 10,
		/obj/item/clothing/shoes/rainbow = 1,
	)

	contraband = list(/obj/item/clothing/shoes/orange = 5)

	prices = list(
		/obj/item/clothing/shoes/black = 20,
		/obj/item/clothing/shoes/brown = 20,
		/obj/item/clothing/shoes/blue = 20,
		/obj/item/clothing/shoes/green = 20,
		/obj/item/clothing/shoes/yellow = 20,
		/obj/item/clothing/shoes/purple = 20,
		/obj/item/clothing/shoes/red = 20,
		/obj/item/clothing/shoes/white = 20,
		/obj/item/clothing/shoes/laceup = 40,
		/obj/item/clothing/shoes/sandal = 20,
		/obj/item/clothing/shoes/jackboots = 20,
		/obj/item/clothing/shoes/winterboots = 20,
		/obj/item/clothing/shoes/cowboy = 20,
		/obj/item/clothing/shoes/cowboy/black = 20,
		/obj/item/clothing/shoes/orange = 40,
		/obj/item/clothing/shoes/rainbow = 40,
	)

	refill_canister = /obj/item/vending_refill/shoedispenser

/obj/machinery/economy/vending/shoedispenser/free
	prices = list()

//don't forget to change the refill size if you change the machine's contents!
/obj/machinery/economy/vending/clothing
	name = "\improper ClothesMate" //renamed to make the slogan rhyme
	desc = "A vending machine for clothing."
	icon_state = "clothes"
	icon_lightmask = "base_drobe"
	icon_panel = "drobe"
	slogan_list = list(
		"Dress for success!",
		"Prepare to look swagalicious!",
		"Look at all this free swag!",
		"Why leave style up to fate? Use the ClothesMate!",
	)
	vend_delay = 15
	vend_reply = "Thank you for using the ClothesMate!"
	category = VENDOR_TYPE_CLOTHING
	products = list(
		/obj/item/clothing/suit/ianshirt = 2,
		/obj/item/clothing/under/misc/overalls = 2,
		/obj/item/clothing/under/misc/mailman = 1,
		/obj/item/clothing/under/suit/navy = 2,
		/obj/item/clothing/under/suit/really_black = 2,
		/obj/item/clothing/under/suit/checkered = 1,
		/obj/item/clothing/suit/storage/iaa/blackjacket = 2,
		/obj/item/clothing/under/pants/jeans = 3,
		/obj/item/clothing/under/pants/classicjeans = 3,
		/obj/item/clothing/under/pants/mustangjeans = 1,
		/obj/item/clothing/under/pants/camo = 3,
		/obj/item/clothing/under/pants/blackjeans = 3,
		/obj/item/clothing/under/pants/shorts/jeanshorts = 3,
		/obj/item/clothing/under/pants/khaki = 3,
		/obj/item/clothing/under/pants/white = 3,
		/obj/item/clothing/under/pants/red = 3,
		/obj/item/clothing/under/pants/black = 3,
		/obj/item/clothing/under/pants/tan = 3,
		/obj/item/clothing/under/pants/blue = 3,
		/obj/item/clothing/under/pants/cargo = 3,
		/obj/item/clothing/under/pants/track = 3,
		/obj/item/clothing/suit/tracksuit = 3,
		/obj/item/clothing/suit/tracksuit/green = 3,
		/obj/item/clothing/suit/tracksuit/red = 3,
		/obj/item/clothing/suit/tracksuit/white = 3,
		/obj/item/clothing/suit/jacket/miljacket = 3,
		/obj/item/clothing/suit/jacket/miljacket/white = 3,
		/obj/item/clothing/suit/jacket/miljacket/desert = 3,
		/obj/item/clothing/suit/jacket/miljacket/navy = 3,
		/obj/item/clothing/head/beanie = 3,
		/obj/item/clothing/head/beanie/black = 3,
		/obj/item/clothing/head/beanie/red = 3,
		/obj/item/clothing/head/beanie/green = 3,
		/obj/item/clothing/head/beanie/darkblue = 3,
		/obj/item/clothing/head/beanie/purple = 3,
		/obj/item/clothing/head/beanie/yellow = 3,
		/obj/item/clothing/head/beanie/orange = 3,
		/obj/item/clothing/head/beanie/cyan = 3,
		/obj/item/clothing/head/beanie/christmas = 3,
		/obj/item/clothing/head/beanie/striped = 3,
		/obj/item/clothing/head/beanie/stripedred = 3,
		/obj/item/clothing/head/beanie/stripedblue = 3,
		/obj/item/clothing/head/beanie/stripedgreen = 3,
		/obj/item/clothing/head/beanie/rasta = 3,
		/obj/item/clothing/neck/scarf/red = 3,
		/obj/item/clothing/neck/scarf/green = 3,
		/obj/item/clothing/neck/scarf/darkblue = 3,
		/obj/item/clothing/neck/scarf/purple = 3,
		/obj/item/clothing/neck/scarf/yellow = 3,
		/obj/item/clothing/neck/scarf/orange = 3,
		/obj/item/clothing/neck/scarf/lightblue = 3,
		/obj/item/clothing/neck/scarf/white = 3,
		/obj/item/clothing/neck/scarf/black = 3,
		/obj/item/clothing/neck/scarf/zebra = 3,
		/obj/item/clothing/neck/scarf/christmas = 3,
		/obj/item/clothing/neck/scarf/stripedred = 3,
		/obj/item/clothing/neck/scarf/stripedblue = 3,
		/obj/item/clothing/neck/scarf/stripedgreen = 3,
		/obj/item/clothing/neck/tie/blue = 3,
		/obj/item/clothing/neck/tie/red = 3,
		/obj/item/clothing/neck/tie/black = 3,
		/obj/item/clothing/accessory/waistcoat = 2,
		/obj/item/clothing/under/dress/sundress = 2,
		/obj/item/clothing/under/dress/stripeddress = 2,
		/obj/item/clothing/under/dress/sailordress = 2,
		/obj/item/clothing/under/dress/redeveninggown = 2,
		/obj/item/clothing/under/dress/blacktango = 2,
		/obj/item/clothing/suit/hooded/wintercoat = 3,
		/obj/item/clothing/suit/jacket/bomber = 3,
		/obj/item/clothing/suit/hooded/hoodie = 3,
		/obj/item/clothing/suit/hooded/hoodie/blue = 3,
		/obj/item/clothing/suit/jacket/motojacket = 3,
		/obj/item/clothing/suit/jacket/leather = 1,
		/obj/item/clothing/suit/blacktrenchcoat = 3,
		/obj/item/clothing/suit/browntrenchcoat = 3,
		/obj/item/clothing/mask/bandana = 2,
		/obj/item/clothing/mask/bandana/black = 2,
		/obj/item/clothing/glasses/regular = 2,
		/obj/item/clothing/glasses/sunglasses_fake = 2,
		/obj/item/clothing/glasses/goggles = 2,
		/obj/item/clothing/gloves/fingerless = 2,
		/obj/item/storage/belt/fannypack = 1,
		/obj/item/storage/belt/fannypack/blue = 1,
		/obj/item/storage/belt/fannypack/red = 1,
		/obj/item/clothing/neck/cloak/mantle = 2,
		/obj/item/clothing/neck/cloak/old = 1,
		/obj/item/clothing/neck/cloak/regal = 2,
	)

	contraband = list(
		/obj/item/clothing/under/syndicate/tacticool = 1,
		/obj/item/clothing/mask/balaclava = 1,
		/obj/item/clothing/head/ushanka = 1,
		/obj/item/clothing/under/costume/soviet = 1,
		/obj/item/clothing/suit/pimpcoat/white = 3,
		/obj/item/storage/belt/fannypack/black = 1,
	)

	prices = list(
		/obj/item/clothing/under/suit/navy = 75,
		/obj/item/clothing/under/misc/overalls = 75,
		/obj/item/clothing/under/suit/checkered = 125,
		/obj/item/clothing/under/suit/really_black = 75,
		/obj/item/clothing/suit/storage/iaa/blackjacket = 75,
		/obj/item/clothing/under/pants/jeans = 75,
		/obj/item/clothing/under/pants/classicjeans = 75,
		/obj/item/clothing/under/pants/mustangjeans = 100,
		/obj/item/clothing/under/pants/camo = 75,
		/obj/item/clothing/under/pants/blackjeans = 75,
		/obj/item/clothing/under/pants/shorts/jeanshorts = 75,
		/obj/item/clothing/under/pants/khaki = 75,
		/obj/item/clothing/under/pants/white = 75,
		/obj/item/clothing/under/pants/red = 75,
		/obj/item/clothing/under/pants/black = 75,
		/obj/item/clothing/under/pants/tan = 75,
		/obj/item/clothing/under/pants/blue = 75,
		/obj/item/clothing/under/pants/cargo = 75,
		/obj/item/clothing/under/pants/track = 75,
		/obj/item/clothing/suit/tracksuit = 75,
		/obj/item/clothing/suit/tracksuit/green = 75,
		/obj/item/clothing/suit/tracksuit/red = 75,
		/obj/item/clothing/suit/tracksuit/white = 75,
		/obj/item/clothing/suit/jacket/miljacket = 75,
		/obj/item/clothing/suit/jacket/miljacket/white = 75,
		/obj/item/clothing/suit/jacket/miljacket/desert = 75,
		/obj/item/clothing/suit/jacket/miljacket/navy = 75,
		/obj/item/clothing/head/beanie = 30,
		/obj/item/clothing/head/beanie/black = 30,
		/obj/item/clothing/head/beanie/red = 30,
		/obj/item/clothing/head/beanie/green = 30,
		/obj/item/clothing/head/beanie/darkblue = 30,
		/obj/item/clothing/head/beanie/purple = 30,
		/obj/item/clothing/head/beanie/yellow = 30,
		/obj/item/clothing/head/beanie/orange = 30,
		/obj/item/clothing/head/beanie/cyan = 30,
		/obj/item/clothing/head/beanie/christmas = 40,
		/obj/item/clothing/head/beanie/striped = 40,
		/obj/item/clothing/head/beanie/stripedred = 40,
		/obj/item/clothing/head/beanie/stripedblue = 40,
		/obj/item/clothing/head/beanie/stripedgreen = 40,
		/obj/item/clothing/head/beanie/rasta = 40,
		/obj/item/clothing/neck/scarf/red = 20,
		/obj/item/clothing/neck/scarf/green = 20,
		/obj/item/clothing/neck/scarf/darkblue = 20,
		/obj/item/clothing/neck/scarf/purple = 20,
		/obj/item/clothing/neck/scarf/yellow = 20,
		/obj/item/clothing/neck/scarf/orange = 20,
		/obj/item/clothing/neck/scarf/lightblue = 20,
		/obj/item/clothing/neck/scarf/white = 20,
		/obj/item/clothing/neck/scarf/black = 20,
		/obj/item/clothing/neck/scarf/zebra = 20,
		/obj/item/clothing/neck/scarf/christmas = 20,
		/obj/item/clothing/neck/scarf/stripedred = 20,
		/obj/item/clothing/neck/scarf/stripedblue = 20,
		/obj/item/clothing/neck/scarf/stripedgreen = 20,
		/obj/item/clothing/neck/tie/blue = 20,
		/obj/item/clothing/neck/tie/red = 20,
		/obj/item/clothing/neck/tie/black = 20,
		/obj/item/clothing/accessory/waistcoat = 20,
		/obj/item/clothing/under/dress/sundress = 75,
		/obj/item/clothing/under/dress/stripeddress = 75,
		/obj/item/clothing/under/dress/sailordress = 75,
		/obj/item/clothing/under/dress/redeveninggown = 100,
		/obj/item/clothing/under/dress/blacktango = 100,
		/obj/item/clothing/suit/hooded/wintercoat = 75,
		/obj/item/clothing/suit/jacket/bomber = 75,
		/obj/item/clothing/suit/hooded/hoodie = 75,
		/obj/item/clothing/suit/hooded/hoodie/blue = 75,
		/obj/item/clothing/suit/jacket/motojacket = 75,
		/obj/item/clothing/suit/jacket/leather = 100,
		/obj/item/clothing/suit/blacktrenchcoat = 75,
		/obj/item/clothing/suit/browntrenchcoat = 75,
		/obj/item/clothing/glasses/regular = 20,
		/obj/item/clothing/glasses/sunglasses_fake = 20,
		/obj/item/clothing/glasses/goggles = 40,
		/obj/item/clothing/suit/ianshirt = 75,
		/obj/item/clothing/mask/bandana = 30,
		/obj/item/clothing/mask/bandana/black = 30,
		/obj/item/clothing/gloves/fingerless = 10,
		/obj/item/storage/belt/fannypack = 50,
		/obj/item/storage/belt/fannypack/blue = 50,
		/obj/item/storage/belt/fannypack/red = 50,
		/obj/item/clothing/neck/cloak/mantle = 20,
		/obj/item/clothing/neck/cloak/old = 20,
		/obj/item/clothing/neck/cloak/regal = 30,
		/obj/item/clothing/suit/pimpcoat/white = 500,
		/obj/item/clothing/under/misc/mailman = 100,
	)

	refill_canister = /obj/item/vending_refill/clothing

/obj/machinery/economy/vending/clothing/free
	prices = list()

/obj/machinery/economy/vending/magivend
	name = "\improper MagiVend"
	desc = "A magic vending machine."
	icon_state = "MagiVend"
	slogan_list = list(
		"Sling spells the proper way with MagiVend!",
		"Be your own Houdini! Use MagiVend!",
	)
	vend_delay = 15
	vend_reply = "Have an enchanted evening!"
	category = VENDOR_TYPE_CLOTHING
	ads_list = list(
		"FJKLFJSD",
		"AJKFLBJAKL",
		"1234 LOONIES LOL!",
		">MFW",
		"Kill them fuckers!",
		"GET DAT FUKKEN DISK",
		"HONK!",
		"EI NATH",
		"Destroy the station!",
		"Admin conspiracies since forever!",
		"Space-time bending hardware!",
	)

	products = list(
		/obj/item/clothing/head/wizard = 1,
		/obj/item/clothing/suit/wizrobe = 1,
		/obj/item/clothing/head/wizard/red = 1,
		/obj/item/clothing/suit/wizrobe/red = 1,
		/obj/item/clothing/shoes/sandal = 1,
		/obj/item/clothing/suit/wizrobe/clown = 1,
		/obj/item/clothing/head/wizard/clown = 1,
		/obj/item/clothing/mask/gas/clownwiz = 1,
		/obj/item/clothing/shoes/clown_shoes/magical = 1,
		/obj/item/dnainjector/comic = 1,
		/obj/item/bio_chip_implanter/sad_trombone = 1,
		/obj/item/clothing/suit/wizrobe/mime = 1,
		/obj/item/clothing/head/wizard/mime = 1,
		/obj/item/clothing/mask/gas/mime/wizard = 1,
		/obj/item/clothing/shoes/sandal/marisa = 1,
		/obj/item/staff = 2,
	)

	contraband = list(/obj/item/reagent_containers/glass/bottle/wizarditis = 1)
	armor = list(MELEE = 100, BULLET = 100, LASER = 100, ENERGY = 100, BOMB = 0, RAD = 0, FIRE = 100, ACID = 50)
	resistance_flags = FIRE_PROOF
	tiltable = FALSE // don't let a poor wizard screw themselves

/obj/machinery/economy/vending/autodrobe
	name = "\improper AutoDrobe"
	desc = "A vending machine for costumes."
	icon_state = "theater"
	icon_lightmask = "theater"
	icon_deny = "theater_deny"
	slogan_list = list(
		"Dress for success!",
		"Suited and booted!",
		"It's show time!",
		"Why leave style up to fate? Use AutoDrobe!",
	)

	vend_delay = 15
	vend_reply = "Thank you for using AutoDrobe!"
	category = VENDOR_TYPE_CLOTHING
	products = list(
		/obj/item/clothing/suit/chickensuit = 1,
		/obj/item/clothing/head/chicken = 1,
		/obj/item/clothing/under/costume/gladiator = 1,
		/obj/item/clothing/head/helmet/gladiator = 1,
		/obj/item/clothing/under/misc/gimmick_captain_suit = 1,
		/obj/item/clothing/head/flatcap = 1,
		/obj/item/clothing/suit/storage/labcoat/mad = 1,
		/obj/item/clothing/glasses/gglasses = 1,
		/obj/item/clothing/under/dress/schoolgirl = 1,
		/obj/item/clothing/suit/toggle/owlwings = 1,
		/obj/item/clothing/under/costume/owl = 1,
		/obj/item/clothing/mask/gas/owl_mask = 1,
		/obj/item/clothing/suit/toggle/owlwings/griffinwings = 1,
		/obj/item/clothing/under/costume/griffin = 1,
		/obj/item/clothing/shoes/griffin = 1,
		/obj/item/clothing/head/griffin = 1,
		/obj/item/clothing/under/suit/black = 1,
		/obj/item/clothing/head/that = 1,
		/obj/item/clothing/under/costume/kilt = 1,
		/obj/item/clothing/glasses/monocle = 1,
		/obj/item/clothing/head/bowlerhat = 1,
		/obj/item/cane = 1,
		/obj/item/clothing/under/misc/sl_suit = 1,
		/obj/item/clothing/mask/fakemoustache = 1,
		/obj/item/clothing/suit/bio_suit/plaguedoctorsuit = 1,
		/obj/item/clothing/head/plaguedoctorhat = 1,
		/obj/item/clothing/mask/gas/plaguedoctor = 1,
		/obj/item/clothing/suit/apron = 1,
		/obj/item/clothing/under/misc/waiter = 1,
		/obj/item/clothing/accessory/cowboyshirt = 1,
		/obj/item/clothing/accessory/cowboyshirt/navy = 1,
		/obj/item/clothing/under/costume/pirate = 1,
		/obj/item/clothing/suit/pirate_brown = 1,
		/obj/item/clothing/suit/pirate_black = 1,
		/obj/item/clothing/head/cool_bandana = 1,
		/obj/item/clothing/under/costume/pirate_rags = 1,
		/obj/item/clothing/head/pirate = 1,
		/obj/item/clothing/under/costume/soviet = 1,
		/obj/item/clothing/head/ushanka = 1,
		/obj/item/clothing/suit/imperium_monk = 1,
		/obj/item/clothing/mask/gas/cyborg = 1,
		/obj/item/clothing/suit/holidaypriest = 1,
		/obj/item/clothing/head/wizard/marisa/fake = 1,
		/obj/item/clothing/suit/wizrobe/marisa/fake = 1,
		/obj/item/clothing/under/dress/sundress = 1,
		/obj/item/clothing/head/witchwig = 1,
		/obj/item/staff/broom = 1,
		/obj/item/clothing/suit/wizrobe/fake = 1,
		/obj/item/clothing/head/wizard/fake = 1,
		/obj/item/staff = 3,
		/obj/item/clothing/mask/gas/clown_hat/sexy = 1,
		/obj/item/clothing/under/rank/civilian/clown/sexy = 1,
		/obj/item/clothing/mask/gas/sexymime = 1,
		/obj/item/clothing/under/rank/civilian/mime/sexy = 1,
		/obj/item/clothing/suit/suspenders = 1,
		/obj/item/clothing/mask/face/bat = 1,
		/obj/item/clothing/mask/face/bee = 1,
		/obj/item/clothing/mask/face/bear = 1,
		/obj/item/clothing/mask/face/raven = 1,
		/obj/item/clothing/mask/face/jackal = 1,
		/obj/item/clothing/mask/face/fox = 1,
		/obj/item/clothing/mask/face/tribal = 1,
		/obj/item/clothing/mask/face/rat = 1,
		/obj/item/clothing/mask/fake_beard = 1,
		/obj/item/clothing/suit/apron/overalls = 1,
		/obj/item/clothing/head/rabbitears = 1,
		/obj/item/clothing/head/sombrero = 1,
		/obj/item/clothing/suit/poncho = 1,
		/obj/item/clothing/suit/poncho/green = 1,
		/obj/item/clothing/suit/poncho/red = 1,
		/obj/item/clothing/neck/tie/horrible = 1,
		/obj/item/clothing/under/costume/maid = 1,
		/obj/item/clothing/under/costume/janimaid = 1,
		/obj/item/clothing/under/costume/jester = 1,
		/obj/item/clothing/head/jester = 1,
		/obj/item/clothing/under/pants/camo = 1,
		/obj/item/clothing/shoes/singery = 1,
		/obj/item/clothing/under/costume/singery = 1,
		/obj/item/clothing/shoes/singerb = 1,
		/obj/item/clothing/under/costume/singerb = 1,
		/obj/item/clothing/suit/hooded/carp_costume = 1,
		/obj/item/clothing/suit/hooded/bee_costume = 1,
		/obj/item/clothing/suit/snowman = 1,
		/obj/item/clothing/head/snowman = 1,
		/obj/item/clothing/head/cueball = 1,
		/obj/item/clothing/under/misc/scratch = 1,
		/obj/item/clothing/under/dress/victdress = 1,
		/obj/item/clothing/under/dress/victdress/red = 1,
		/obj/item/clothing/suit/victcoat = 1,
		/obj/item/clothing/suit/victcoat/red = 1,
		/obj/item/clothing/under/suit/victsuit = 1,
		/obj/item/clothing/under/suit/victsuit/redblk = 1,
		/obj/item/clothing/under/suit/victsuit/red = 1,
		/obj/item/clothing/suit/tailcoat = 1,
		/obj/item/clothing/under/costume/tourist_suit = 1,
		/obj/item/clothing/suit/draculacoat = 1,
		/obj/item/clothing/head/zepelli = 1,
		/obj/item/clothing/under/misc/redhawaiianshirt = 1,
		/obj/item/clothing/under/misc/pinkhawaiianshirt = 1,
		/obj/item/clothing/under/misc/bluehawaiianshirt = 1,
		/obj/item/clothing/under/misc/orangehawaiianshirt = 1,
		/obj/item/clothing/under/misc/baseball = 1,
		/obj/item/clothing/under/misc/baseball/solgov = 1,
		/obj/item/clothing/under/misc/baseball/nanotrasen = 1,
		/obj/item/clothing/head/soft/black = 1,
		/obj/item/clothing/head/soft/baseball_tsf = 1,
		/obj/item/clothing/head/soft/baseball_nt = 1,
		/obj/item/clothing/suit/jacket/varsity = 1,
		/obj/item/clothing/suit/jacket/varsity_sport = 1,
		/obj/item/clothing/suit/jacket/varsity_blood = 1,
		/obj/item/clothing/suit/jacket/driver = 1,
		/obj/item/clothing/suit/hgpirate = 1,
		/obj/item/clothing/head/hgpiratecap = 1,
		/obj/item/clothing/head/helmet/roman/fake = 1,
		/obj/item/clothing/head/helmet/roman/legionaire/fake = 1,
		/obj/item/clothing/under/costume/roman = 1,
		/obj/item/clothing/shoes/roman = 1,
		/obj/item/shield/riot/roman/fake = 1,
		/obj/item/clothing/under/costume/cuban_suit = 1,
		/obj/item/clothing/head/cuban_hat = 1,
		/obj/item/clothing/head/turban_orange = 1,
		/obj/item/clothing/head/turban_green = 1,
		/obj/item/clothing/head/eboshi = 1,
		/obj/item/clothing/head/kippah = 1,
		/obj/item/clothing/head/shtreimel = 1,
		/obj/item/clothing/head/hijab = 1,
		/obj/item/clothing/suit/hooded/costume/cassock = 1,
		/obj/item/clothing/suit/hooded/costume/nun = 1,
		/obj/item/clothing/suit/costume/bana = 1,
		/obj/item/clothing/suit/costume/joue = 1,
		/obj/item/clothing/suit/costume/miko = 1,
		/obj/item/clothing/suit/costume/hasidic_coat = 1,
		/obj/item/clothing/under/costume/kasaya = 1,
		/obj/item/clothing/under/costume/modestgreen = 1,
		/obj/item/clothing/under/costume/thobe = 1,
		/obj/item/clothing/neck/cloak/tallit = 1,
		/obj/item/clothing/head/santahat = 3,
		/obj/item/clothing/suit/santa = 1,
	)

	contraband = list(
		/obj/item/clothing/suit/judgerobe = 1,
		/obj/item/clothing/head/powdered_wig = 1,
		/obj/item/gun/magic/wand = 1,
		/obj/item/clothing/mask/balaclava = 1,
		/obj/item/clothing/mask/horsehead = 2,
	)

	prices = list(
		/obj/item/clothing/suit/chickensuit = 100,
		/obj/item/clothing/head/chicken = 50,
		/obj/item/clothing/under/costume/gladiator = 100,
		/obj/item/clothing/head/helmet/gladiator = 50,
		/obj/item/clothing/under/misc/gimmick_captain_suit = 100,
		/obj/item/clothing/head/flatcap = 30,
		/obj/item/clothing/suit/storage/labcoat/mad = 75,
		/obj/item/clothing/glasses/gglasses = 20,
		/obj/item/clothing/under/dress/schoolgirl = 75,
		/obj/item/clothing/suit/toggle/owlwings = 120,
		/obj/item/clothing/under/costume/owl = 100,
		/obj/item/clothing/mask/gas/owl_mask = 50,
		/obj/item/clothing/suit/toggle/owlwings/griffinwings = 120,
		/obj/item/clothing/under/costume/griffin = 100,
		/obj/item/clothing/shoes/griffin = 30,
		/obj/item/clothing/head/griffin = 50,
		/obj/item/clothing/under/suit/black = 75,
		/obj/item/clothing/head/that = 30,
		/obj/item/clothing/under/costume/kilt = 75,
		/obj/item/clothing/glasses/monocle = 30,
		/obj/item/clothing/head/bowlerhat = 20,
		/obj/item/cane = 50,
		/obj/item/clothing/under/misc/sl_suit = 75,
		/obj/item/clothing/mask/fakemoustache = 20,
		/obj/item/clothing/suit/bio_suit/plaguedoctorsuit = 100,
		/obj/item/clothing/head/plaguedoctorhat = 40,
		/obj/item/clothing/mask/gas/plaguedoctor = 50,
		/obj/item/clothing/suit/apron = 75,
		/obj/item/clothing/under/misc/waiter = 75,
		/obj/item/clothing/accessory/cowboyshirt = 75,
		/obj/item/clothing/accessory/cowboyshirt/navy = 75,
		/obj/item/clothing/under/costume/pirate = 100,
		/obj/item/clothing/suit/pirate_brown = 100,
		/obj/item/clothing/suit/pirate_black = 100,
		/obj/item/clothing/head/cool_bandana = 50,
		/obj/item/clothing/under/costume/pirate_rags = 100,
		/obj/item/clothing/head/pirate = 50,
		/obj/item/clothing/under/costume/soviet = 100,
		/obj/item/clothing/head/ushanka = 50,
		/obj/item/clothing/suit/imperium_monk = 120,
		/obj/item/clothing/mask/gas/cyborg = 50,
		/obj/item/clothing/suit/holidaypriest = 100,
		/obj/item/clothing/head/wizard/marisa/fake = 50,
		/obj/item/clothing/suit/wizrobe/marisa/fake = 100,
		/obj/item/clothing/under/dress/sundress = 75,
		/obj/item/clothing/head/witchwig = 50,
		/obj/item/staff/broom = 50,
		/obj/item/clothing/suit/wizrobe/fake = 75,
		/obj/item/clothing/head/wizard/fake = 75,
		/obj/item/staff = 50,
		/obj/item/clothing/mask/gas/clown_hat/sexy = 100,
		/obj/item/clothing/under/rank/civilian/clown/sexy = 100,
		/obj/item/clothing/mask/gas/sexymime = 100,
		/obj/item/clothing/under/rank/civilian/mime/sexy = 100,
		/obj/item/clothing/suit/suspenders = 50,
		/obj/item/clothing/mask/face/bat = 100,
		/obj/item/clothing/mask/face/bee = 100,
		/obj/item/clothing/mask/face/bear = 100,
		/obj/item/clothing/mask/face/raven = 100,
		/obj/item/clothing/mask/face/jackal = 100,
		/obj/item/clothing/mask/face/fox = 100,
		/obj/item/clothing/mask/face/tribal = 100,
		/obj/item/clothing/mask/face/rat = 100,
		/obj/item/clothing/mask/fake_beard = 50,
		/obj/item/clothing/suit/apron/overalls = 75,
		/obj/item/clothing/head/rabbitears = 75,
		/obj/item/clothing/head/sombrero = 40,
		/obj/item/clothing/suit/poncho = 75,
		/obj/item/clothing/suit/poncho/green = 75,
		/obj/item/clothing/suit/poncho/red = 75,
		/obj/item/clothing/neck/tie/horrible = 30,
		/obj/item/clothing/under/costume/maid = 75,
		/obj/item/clothing/under/costume/janimaid = 75,
		/obj/item/clothing/under/costume/jester = 100,
		/obj/item/clothing/head/jester = 50,
		/obj/item/clothing/under/pants/camo = 75,
		/obj/item/clothing/shoes/singery = 20,
		/obj/item/clothing/under/costume/singery = 75,
		/obj/item/clothing/shoes/singerb = 20,
		/obj/item/clothing/under/costume/singerb = 75,
		/obj/item/clothing/suit/hooded/carp_costume = 120,
		/obj/item/clothing/suit/hooded/bee_costume = 120,
		/obj/item/clothing/suit/snowman = 120,
		/obj/item/clothing/head/snowman = 50,
		/obj/item/clothing/head/cueball = 50,
		/obj/item/clothing/under/misc/scratch = 75,
		/obj/item/clothing/under/dress/victdress = 100,
		/obj/item/clothing/under/dress/victdress/red = 100,
		/obj/item/clothing/suit/victcoat = 100,
		/obj/item/clothing/suit/victcoat/red = 100,
		/obj/item/clothing/under/suit/victsuit = 100,
		/obj/item/clothing/under/suit/victsuit/redblk = 100,
		/obj/item/clothing/under/suit/victsuit/red = 100,
		/obj/item/clothing/suit/tailcoat = 75,
		/obj/item/clothing/under/costume/tourist_suit = 75,
		/obj/item/clothing/suit/draculacoat = 100,
		/obj/item/clothing/head/zepelli = 50,
		/obj/item/clothing/under/misc/redhawaiianshirt = 75,
		/obj/item/clothing/under/misc/pinkhawaiianshirt = 75,
		/obj/item/clothing/under/misc/bluehawaiianshirt = 75,
		/obj/item/clothing/under/misc/orangehawaiianshirt = 75,
		/obj/item/clothing/under/misc/baseball = 75,
		/obj/item/clothing/under/misc/baseball/solgov = 75,
		/obj/item/clothing/under/misc/baseball/nanotrasen = 75,
		/obj/item/clothing/head/soft/black = 50,
		/obj/item/clothing/head/soft/baseball_tsf = 50,
		/obj/item/clothing/head/soft/baseball_nt = 50,
		/obj/item/clothing/suit/jacket/varsity = 200,
		/obj/item/clothing/suit/jacket/varsity_sport = 200,
		/obj/item/clothing/suit/jacket/varsity_blood = 200,
		/obj/item/clothing/suit/jacket/driver = 350,
		/obj/item/clothing/suit/hgpirate = 125,
		/obj/item/clothing/head/hgpiratecap = 75,
		/obj/item/clothing/head/helmet/roman/fake = 75,
		/obj/item/clothing/head/helmet/roman/legionaire/fake = 75,
		/obj/item/clothing/under/costume/roman = 125,
		/obj/item/clothing/shoes/roman = 40,
		/obj/item/shield/riot/roman/fake = 75,
		/obj/item/clothing/under/costume/cuban_suit = 125,
		/obj/item/clothing/head/cuban_hat = 75,
		/obj/item/clothing/head/turban_orange = 50,
		/obj/item/clothing/head/turban_green = 50,
		/obj/item/clothing/head/eboshi = 50,
		/obj/item/clothing/head/kippah = 50,
		/obj/item/clothing/head/shtreimel = 75,
		/obj/item/clothing/head/hijab = 50,
		/obj/item/clothing/suit/hooded/costume/cassock = 100,
		/obj/item/clothing/suit/hooded/costume/nun = 100,
		/obj/item/clothing/suit/costume/bana = 100,
		/obj/item/clothing/suit/costume/joue = 100,
		/obj/item/clothing/suit/costume/miko = 100,
		/obj/item/clothing/suit/costume/hasidic_coat = 100,
		/obj/item/clothing/under/costume/kasaya = 100,
		/obj/item/clothing/under/costume/modestgreen = 100,
		/obj/item/clothing/under/costume/thobe = 100,
		/obj/item/clothing/neck/cloak/tallit = 75,
		/obj/item/clothing/head/santahat = 50,
		/obj/item/clothing/suit/santa = 200,
	)

	refill_canister = /obj/item/vending_refill/autodrobe

/obj/machinery/economy/vending/autodrobe/free
	prices = list()
