GLOBAL_LIST_INIT(fortune_cookie_messages, list("If you feel you are right, stand firmly by your convictions.",
"A stranger is a friend you have not spoken to yet.",
"Yesterday, you said tomorrow. Just do it!",
"Do, or do not. There is no try.",
"Fear leads to anger. Anger leads to hate. Hate leads to suffering.",
"Luck always favours the prepared mind.",
"A smile is your passport into the hearts of others.",
"Hard work pays off in the future, laziness pays off now.",
"Change can hurt, but it leads a path to something better.",
"If winter comes soon, can spring be far behind?",
"Love with your heart; use your head for everything else.",
"The man on the top of the mountain did not fall there.",
"The greatest risk is not taking one.",
"Strategy without tactics is the slowest route to victory.<br>Tactics without strategy is the noise before defeat.",
"If you are far from the enemy, make him believe you are near.",
"He who knows when he can fight and when he cannot, will be victorious.",
"A clever person solves a problem. A wise person avoids it.",
"When fighting for freedom, never wear new pants.",
"If you want the rainbow, you must put up with the rain.",
"Get ready! Good fortune comes in bunches.",
"An exciting opportunity lies ahead of you.",
"A journey of a thousand miles begins with a single step.",
"Expect the unexpected.",
"Live this day as if it were your last.",
"Remember the compliments you receive; forget the insults.",
"A chance meeting opens new doors to success and friendship.",
"Failure is the mother of success.",
"A rolling stone gathers no moss.",
"When life gives you lemons, make lemonade.",
"You will inherit some money or a small piece of land.",
"Happy news is on its way to you.",
"A pleasant surprise is in store for you.",
"You will be invited to an exciting event.",
"Keep your plans secret for now.",
"You will live a long, happy life.",
"When one door closes, another opens.",
"Life is a canvas, and you are its painter.",
"Failure to prepare is to prepare to fail.",
"Beware the robot that thinks for itself.",
"The early bird gets the worm, but the second mouse gets the cheese.",
"Don't pursue happiness - create it.",
"Courage is not the absence of fear; it is the conquest of it.",
"All things are difficult before they are easy.",
"A ship in harbour is safe, but that's not why ships are built.",
"Hardly anyone knows how much is gained by ignoring the future.",
"The wise man is the one that makes you think that he is dumb.",
"Hatred outlives the hateful.",
"The fatal flaw in every plan is the assumption that you know more than the enemy",
"A journey of a thousand miles begins with a single step.",
"Dig the well before you are thirsty.",
"Be not afraid of growing slowly, be afraid only of standing still.",
"Do not remove a fly from your friend's forehead with a hatchet.",
"A foolish man listens to his heart.<br>A wise man listens to cookies.",
"Thank you! But your fortune is in another cookie!",
"The greatest danger could be your stupidity.",
"He who laughs at himself never runs out of things to laugh at.",
"Help! I'm being held prisoner in a Nanotrasen bakery!"))
