GLOBAL_LIST_INIT(ai_names, file2list("config/names/ai.txt"))
GLOBAL_LIST_INIT(wizard_first, file2list("config/names/wizardfirst.txt"))
GLOBAL_LIST_INIT(wizard_second, file2list("config/names/wizardsecond.txt"))
// GLOBAL_LIST_INIT(ninja_titles, file2list("config/names/ninjatitle.txt")) // This is kept because we technically still have these files in the code in case we ever want to use them, but is currently unused
GLOBAL_LIST_INIT(ninja_names, file2list("config/names/ninjaname.txt"))
GLOBAL_LIST_INIT(deathsquad_names, file2list("config/names/deathsquad.txt"))
GLOBAL_LIST_INIT(first_names_male, file2list("config/names/first_male.txt"))
GLOBAL_LIST_INIT(first_names_female, file2list("config/names/first_female.txt"))
GLOBAL_LIST_INIT(last_names, file2list("config/names/last.txt"))
GLOBAL_LIST_INIT(first_names_female_slime, file2list("config/names/first_female_slime.txt"))
GLOBAL_LIST_INIT(first_names_male_slime, file2list("config/names/first_male_slime.txt"))
GLOBAL_LIST_INIT(last_names_slime, file2list("config/names/last_slime.txt"))
GLOBAL_LIST_INIT(first_names_female_vulp, file2list("config/names/first_female_vulp.txt"))
GLOBAL_LIST_INIT(first_names_male_vulp, file2list("config/names/first_male_vulp.txt"))
GLOBAL_LIST_INIT(last_names_vulp, file2list("config/names/last_vulp.txt"))
GLOBAL_LIST_INIT(clown_names, file2list("config/names/clown.txt"))
GLOBAL_LIST_INIT(mime_names, file2list("config/names/mime.txt"))
GLOBAL_LIST_INIT(golem_names, file2list("config/names/golem.txt"))
GLOBAL_LIST_INIT(megacarp_first_names, file2list("strings/names/megacarp1.txt"))
GLOBAL_LIST_INIT(megacarp_last_names, file2list("strings/names/megacarp2.txt"))
GLOBAL_LIST_INIT(first_names_soviet, file2list("config/names/first_soviet_male.txt"))
GLOBAL_LIST_INIT(last_names_soviet, file2list("config/names/last_soviet_male.txt"))

GLOBAL_LIST_INIT(verbs, file2list("config/names/verbs.txt"))
// GLOBAL_LIST_INIT(nouns, file2list("config/names/nouns.txt")) // This is kept because we technically still have these files in the code in case we ever want to use them, but is currently unused
GLOBAL_LIST_INIT(adjectives, file2list("config/names/adjectives.txt"))
GLOBAL_LIST_INIT(dream_strings, file2list("config/names/dreams.txt"))
GLOBAL_LIST_INIT(nightmare_strings, file2list("config/names/nightmares.txt"))
GLOBAL_LIST_INIT(codeword_locations, file2list("config/names/codeword_locations.txt"))
GLOBAL_LIST_INIT(codeword_nouns, file2list("config/names/codeword_nouns.txt"))
//loaded on startup because of "
//would include in rsc if ' was used
