blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://www.paradisestation.org/forum/60-suggestions/
    about: Please place all feature requests here.
  - name: Exploit Reports
    url: https://www.paradisestation.org/forum/179-exploit-reports/
    about: If your issue is an ingame exploit that allows players to gain an unfair advantage, or an issue which could affect server stability or security, please file it here so that it is safe from prying eyes.
