name: "Issue Report"
description: "File an issue report to make us aware of a bug or issue."
body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to complete this issue report.<br>
        Please ensure the title is clear and descriptive to help others
        locate and understand the report more easily.<br>

        If you believe this is an exploit, please [report it on the forums instead](https://www.paradisestation.org/forum/179-exploit-reports/).<br>

        What is an exploit? [Check out our documentation here for more information](https://devdocs.paradisestation.org/contributing/exploits/)!

  - type: input
    id: version
    attributes:
      label: BYOND Version
      description: "What BYOND version were you using when the issue occurred? (Find this by pressing the cog in the top-right of the main BYOND menu, then 'About BYOND...') (Required)"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: What is the problem? (Required)
      placeholder: I tried buckling myself to a chair but ended up on lavaland!
    validations:
      required: true

  - type: textarea
    id: what-expected
    attributes:
      label: What did you expect to happen?
      description: Why do you think this is an issue?
      placeholder: I expected to be strapped to a chair.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened instead?
      description: How is what happened different from what you expected?
      placeholder: I got sent to lavaland and died.

  - type: textarea
    id: why-bad
    attributes:
      label: Why is this bad/What are the consequences?
      description: Why do you think this is an important issue?
      placeholder: People sitting in chairs on the station should not end up being devoured by drakes.

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: Steps to reproduce the issue.
      description: The most important section. Review everything you did leading up to causing the issue. (Required)
      placeholder: Find a chair, buckle yourself into it, be eaten by dragon.
    validations:
      required: true

  - type: textarea
    id: when-problem-start
    attributes:
      label: When did the problem start happening?
      description: If your report is about something that used to work but no longer does, when was the last time you remember it working? (Required)
      placeholder: I could sit fine last week, so sometime around then.
    validations:
      required: true

  - type: textarea
    id: extra-information
    attributes:
      label: Extra information
      description: Anything else you can tell us.
      placeholder: "I think this issue was introduced in the following PR https://github.com/ParadiseSS13/Paradise/pull/18477"

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output/runtime error
      description: Please copy and paste any relevant log output or runtime if you have access to this. Please censor any ckeys or IP addresses.
      render: DM
