/**
 * Trade goods for trade destinations
 */
#define TRADE_GOOD_DEFAULT 1
#define TRADE_GOOD_ADMINISTRATIVE 2
#define TRADE_GOOD_CLOTHING 3
#define TRADE_GOOD_SECURITY 4
#define TRADE_GOOD_SPECIAL_SECURITY 5
#define TRADE_GOOD_FOOD 6
#define TRADE_GOOD_ANIMALS 7
#define TRADE_GOOD_MINERALS 8
#define TRADE_GOOD_EMERGENCY 9
#define TRADE_GOOD_GAS 10
#define TRADE_GOOD_MAINTENANCE 11
#define TRADE_GOOD_ELECTRICAL 12
#define TRADE_GOOD_ROBOTICS 13
#define TRADE_GOOD_BIOMEDICAL 14
