#define MUZZLE_FLASH_STRENGTH_WEAK 1
#define MUZZLE_FLASH_STRENGTH_NORMAL 2
#define MUZZLE_FLASH_STRENGTH_STRONG 3

#define MUZZLE_FLASH_RANGE_WEAK 1
#define MUZZLE_FLASH_RANGE_NORMAL 2
#define MUZZLE_FLASH_RANGE_STRONG 3
