//Preference toggles
#define SOUND_ADMINHELP		1
#define SOUND_MIDI			2
#define SOUND_AMBIENCE		4
#define SOUND_LOBBY			8
#define SOUND_STREAMING		16
#define SOUND_HEARTBEAT		32
#define SOUND_BUZZ			64
#define SOUND_INSTRUMENTS	128

#define SOUND_DEFAULT (SOUND_ADMINHELP|SOUND_MIDI|SOUND_AMBIENCE|SOUND_LOBBY|SOUND_STREAMING|SOUND_HEARTBEAT|SOUND_BUZZ|SOUND_INSTRUMENTS)

#define CHAT_OOC		1
#define CHAT_DEAD		2
#define CHAT_GHOSTEARS	4
#define CHAT_GHOSTSIGHT	8
#define CHAT_PRAYER		16
#define CHAT_RADIO		32
#define CHAT_ATTACKLOGS	64
#define CHAT_DEBUGLOGS	128
#define CHAT_LOOC		256
#define CHAT_GHOSTRADIO 512
#define SHOW_TYPING 	1024
#define DISABLE_SCOREBOARD 2048
#define DISABLE_KARMA_REMINDER	4096
#define MEMBER_PUBLIC	8192

#define TOGGLES_DEFAULT (CHAT_OOC|CHAT_DEAD|CHAT_GHOSTEARS|CHAT_GHOSTSIGHT|CHAT_PRAYER|CHAT_RADIO|CHAT_ATTACKLOGS|CHAT_LOOC|MEMBER_PUBLIC)

#define BE_TRAITOR		1
#define BE_OPERATIVE	2
#define BE_CHANGELING	4
#define BE_WIZARD		8
#define BE_MALF			16
#define BE_REV			32
#define BE_ALIEN		64
#define BE_PAI			128
#define BE_CULTIST		256
#define BE_NINJA		512
#define BE_RAIDER		1024
#define BE_VAMPIRE		2048
#define BE_MUTINEER		4096
#define BE_BLOB			8192
#define BE_SHADOWLING	16384
#define BE_REVENANT		32768