// Bannable antag roles
var/global/list/antag_roles = list(
	ROLE_TRAITOR,
	ROLE_OPERATIVE,
	ROLE_CHANGELING,
	ROLE_WIZARD,
	ROLE_REV,
	ROLE_ALIEN,
	ROLE_CULTIST,
	ROLE_BLOB,
	ROLE_NINJA,
	ROLE_SHADOWLING,
	ROLE_RAIDER,
	ROLE_VAMPIRE,
	ROLE_BORER,
	ROLE_DEMON,
	ROLE_REVENANT,
	ROLE_GUARDIAN,
	ROLE_MORPH,
	ROLE_GSPIDER,
)

// Bannable other roles
var/global/list/other_roles = list(
	ROLE_SENTIENT,
	ROLE_NYMPH,
	ROLE_ERT,
	ROLE_GHOST,
	"AntagHUD",
	"Records"
)
