// Bannable antag roles
GLOBAL_LIST_INIT(antag_roles, list(
	ROLE_TRAITOR,
	ROLE_OPERATIVE,
	ROLE_CHANGELING,
	ROLE_WIZARD,
	ROLE_REV,
	ROLE_ALIEN,
	ROLE_CULTIST,
	ROLE_BLOB,
	ROLE_VAMPIRE,
	ROLE_DEMON,
	ROLE_REVENANT,
	ROLE_GUARDIAN,
	ROLE_MORPH,
	ROLE_TSPIDER,
))

// Bannable other roles
GLOBAL_LIST_INIT(other_roles, list(
	ROLE_SENTIENT,
	ROLE_NYMPH,
	ROLE_ERT,
	ROLE_GHOST,
	ROLEBAN_AHUD,
	ROLEBAN_RECORDS,
	ROLE_ELITE
))
