#define SCIENCE_SATELLITE_WEATHER_NODE_ASH_STORM "ASH_STORM"
#define SCIENCE_SATELLITE_WEATHER_NODE_WIND "WIND"
#define SCIENCE_SATELLITE_WEATHER_NODE_VOLCANISM "VOLCANISM"
#define SCIENCE_SATELLITE_WEATHER_NODE_ACID_RAIN "ACID_RAIN"

#define SCIENCE_SATELLITE_WEATHER_NODE_POLE "POLE"

#define SCIENCE_SATELLITE_HAS_METEOROLOGY "METEOROLOGY"
#define SCIENCE_SATELLITE_HAS_MAGNETOMETER "MAGNETOMETER"
#define SCIENCE_SATELLITE_HAS_PLASMA_LAB "PLASMA_LAB"
#define SCIENCE_SATELLITE_NEEDS_VACUUM "NEEDS_VACUUM"
