#define PART_PRIMARY 1
#define PART_SECONDARY 2
#define PART_TRIM 3

#define OPERATION_SPEED_MULT_PER_RATING 0.075
#define EFFICIENCY_MULT_ADD_PER_RATING 0.05

//Smithing machines points defines
#define SMITHING_BASE_POINT_MULT 0.60
#define SMITHING_BASE_SHEET_MULT 0.60
#define SMITHING_POINT_MULT_ADD_PER_RATING 0.10
#define SMITHING_SHEET_MULT_ADD_PER_RATING 0.25
