#define SNPC_MAX_RANGE_FIND 32
#define SNPC_MIN_RANGE_FIND 16
#define SNPC_FUZZY_CHANCE_HIGH 85
#define SNPC_FUZZY_CHANCE_LOW 50
#define SNPC_CHANCE_TALK 15

#define SNPC_BRUTE 1
#define SNPC_STEALTH 2
#define SNPC_MARTYR 3
#define SNPC_PSYCHO 4

#define SNPC_INTERACTING 2
#define SNPC_TRAVEL 4
#define SNPC_FIGHTING 8
#define SNPC_SPECIAL 16

#define AI_TRAIT_ROBUST 2
#define AI_TRAIT_UNROBUST 4
#define AI_TRAIT_SMART 8
#define AI_TRAIT_DUMB 16
#define AI_TRAIT_MEAN 32
#define AI_TRAIT_FRIENDLY 64
#define AI_TRAIT_THIEVING 128