#define SPELL_TARGET_CLOSEST 1
#define SPELL_TARGET_RANDOM 2

#define SPELL_SELECTION_RANGE "range"
#define SPELL_SELECTION_VIEW "view"

#define SMOKE_NONE		0
#define SMOKE_HARMLESS	1
#define SMOKE_COUGHING	2
#define SMOKE_SLEEPING	3

#define INVOCATION_NONE "none"
#define INVOCATION_WHISPER "whisper"
#define INVOCATION_SHOUT "shout"
