#define VR_DROP_NONE 1
#define VR_DROP_ALL 2
#define VR_DROP_BLACKLIST 3
#define VR_DROP_WHITELIST 4

#define VR_SERVER_OFF 0
#define VR_SERVER_ON 1
#define VR_SERVER_EMAG 2

#define VR_ROOM_STATIC 0
#define VR_ROOM_USER 1
#define VR_ROOM_PVP 2