
#undef CONTROL_STATE_IDLE
#undef CONTROL_STATE_PREPARE
#undef CONTROL_STATE_DEPRESSURIZE
#undef CONTROL_STATE_PRESSURIZE
#undef TARGET_NONE
#undef TARGET_INOPEN
#undef TARGET_OUTOPEN
#undef MODE_INTERIOR
#undef MODE_EXTERIOR
