//include game test files in this module in this ifdef
//Keep this sorted alphabetically

#ifdef GAME_TESTS
#include "_game_test_puppeteer.dm"
#include "_game_test.dm"
#include "atmos\test_ventcrawl.dm"
#include "attack_chain\test_attack_chain_cult_dagger.dm"
#include "attack_chain\test_attack_chain_turf.dm"
#include "attack_chain\test_attack_chain_vehicles.dm"
#include "games\test_cards.dm"
#include "jobs\test_job_globals.dm"
#include "test_aicard_icons.dm"
#include "test_announcements.dm"
#include "test_areas_apcs.dm"
#include "test_components.dm"
#include "test_config_sanity.dm"
#include "test_crafting_lists.dm"
#include "test_elements.dm"
#include "test_emotes.dm"
#include "test_init_sanity.dm"
#include "test_log_format.dm"
#include "test_map_templates.dm"
#include "test_map_tests.dm"
#include "test_missing_icons.dm"
#include "test_origin_tech.dm"
#include "test_purchase_reference_test.dm"
#include "test_reagent_id_typos.dm"
#include "test_runner.dm"
#include "test_rustg_version.dm"
#include "test_spawn_humans.dm"
#include "test_spell_targeting_test.dm"
#include "test_sql.dm"
#include "test_status_effect_ids.dm"
#include "test_subsystem_init.dm"
#include "test_subsystem_metric_sanity.dm"
#include "test_timer_sanity.dm"
#endif
