#define PART_PRIMARY 1
#define PART_SECONDARY 2
#define PART_TRIM 3

#define BASE_POINT_MULT 0.60
#define BASE_SHEET_MULT 0.60
#define POINT_MULT_ADD_PER_RATING 0.10
#define SHEET_MULT_ADD_PER_RATING 0.20
#define OPERATION_SPEED_MULT_PER_RATING 0.075
#define EFFICIENCY_MULT_ADD_PER_RATING 0.05
