/obj/structure/closet/secure_closet/engineering_electrical/populate_contents()
	..()
	new /obj/item/inducer/apc(src)
	new /obj/item/inducer/apc(src)
	new/obj/item/clothing/glasses/meson/engine/tray(src)
	new/obj/item/clothing/glasses/meson/engine/tray(src)

/obj/structure/closet/secure_closet/engineering_chief/populate_contents()
	..()
	new /obj/item/whistle(src)
