/obj/structure/closet/secure_closet/engineering_electrical/New()
	..()
	new /obj/item/inducer/apc(src)
	new /obj/item/inducer/apc(src)
	new/obj/item/clothing/glasses/meson/engine/tray(src)
	new/obj/item/clothing/glasses/meson/engine/tray(src)
