/datum/admins/key_down(_key, client/user)
	switch(_key)
		if("F5")
			user.get_admin_say()
			return
		if("F6")
			user.admin_ghost()
			return
		if("F7")
			player_panel_new()
			return
		if("F8")
			user.cmd_admin_pm_panel()
			return
		if("F9")
			user.invisimin()
			return
		if("F10")
			user.get_dead_say()
			return
	..()
