/datum/admins/key_down(_key, client/user)
	switch(_key)
		if("F3")
			if(user.keys_held["Shift"])
				if(!check_rights(R_DEBUG|R_VIEWRUNTIMES))
					return
				if(user in SSdebugview.processing)
					SSdebugview.stop_processing(user)
				else
					SSdebugview.start_processing(user)
				return
		if("F5")
			user.get_admin_say()
			return
		if("F6")
			user.admin_ghost()
			return
		if("F7")
			player_panel_new()
			return
		if("F8")
			user.cmd_admin_pm_panel()
			return
		if("F9")
			user.invisimin()
			return
		if("F10")
			user.get_dead_say()
			return
	..()
