arrowParens: always
bracketSpacing: true
endOfLine: lf
jsxSingleQuote: false
printWidth: 120
proseWrap: preserve
quoteProps: preserve
semi: true
singleQuote: true
tabWidth: 2
trailingComma: es5
overrides:
  - files: 'packages/tgui-setup/helpers.js'
    options:
      trailingComma: es5
      arrowParens: always
