compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

logFilters:
  - code: YN0004
    level: discard
  - code: YN0062
    level: discard

nodeLinker: node-modules

packageExtensions:
  babel-plugin-inferno@*:
    dependencies:
      "@babel/core": "*"

pnpEnableEsmLoader: false

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.3.1.cjs
