
proc/human_roll_mods(var/mob/living/carbon/human/H)
	var/BaseMath = 0
	if(H.handcuffed)
		BaseMath -= rand(0,2)
	if(H.legcuffed)
		BaseMath -= rand(0,2)
	if(H.intent == INTENT_HARM)
		BaseMath += rand(1,3)
	if(H.IsStunned())
		BaseMath -= rand(4,2)
	switch(H.nutrition)
		if(400 to 550)
			BaseMath += pick(0,1)
		if(220 to 275)
			BaseMath += pick(-1,0)
		if(150 to 220)
			BaseMath += pick(-1,0)
		if(100 to 150)
			BaseMath += pick(-2,-0)
		if(1 to 100)
			BaseMath += pick(-3,-2)
		if(-INFINITY to 1)
			BaseMath += pick(-4, -3)
	return BaseMath
