/** Window sizes in pixels */
export enum WindowSize {
  Small = 30,
  Medium = 50,
  Large = 70,
  Width = 275,
}

/** Line lengths for autoexpand */
export enum LineLength {
  Small = 26,
  Medium = 54,
  Large = 82,
}

/**
 * Radio prefixes.
 * Displays the name in the left button, tags a css class.
 */
export const RADIO_PREFIXES = {
  ':r ': 'R-Ear',
  '#r ': 'R-Ear',
  '.r ': 'R-Ear',
  ':l ': 'L-Ear',
  '#l ': 'L-Ear',
  '.l ': 'L-Ear',
  ':i ': 'Intercom',
  '#i ': 'Intercom',
  '.i ': 'Intercom',
  ':h ': 'Dept',
  '#h ': 'Dept',
  '.h ': 'Dept',
  '.р ': 'Dept',
  ':р ': 'Dept',
  ':c ': 'Cmd',
  '#c ': 'Cmd',
  '.c ': 'Cmd',
  '.с ': 'Cmd',
  ':с ': 'Cmd',
  ':n ': 'Sci',
  '#n ': 'Sci',
  '.n ': 'Sci',
  '.т ': 'Sci',
  ':т ': 'Sci',
  ':m ': 'Med',
  '#m ': 'Med',
  '.m ': 'Med',
  '.ь ': 'Med',
  ':ь ': 'Med',
  ':x ': 'Proc',
  '.ч ': 'Proc',
  ':ч ': 'Proc',
  '#x ': 'Proc',
  '.x ': 'Proc',
  ':e ': 'Engi',
  '#e ': 'Engi',
  '.e ': 'Engi',
  '.у ': 'Engi',
  ':у ': 'Engi',
  ':s ': 'Sec',
  '#s ': 'Sec',
  '.s ': 'Sec',
  '.ы ': 'Sec',
  ':ы ': 'Sec',
  ':t ': 'Synd',
  '#t ': 'Synd',
  '.t ': 'Synd',
  '.е ': 'Synd',
  ':е ': 'Synd',
  ':u ': 'Supp',
  '#u ': 'Supp',
  '.u ': 'Supp',
  '.г ': 'Supp',
  ':г ': 'Supp',
  ':z ': 'Serv',
  '#z ': 'Serv',
  '.z ': 'Serv',
  '.я ': 'Serv',
  ':я ': 'Serv',
  ':p ': 'AI',
  '#p ': 'AI',
  '.p ': 'AI',
  '.з ': 'AI',
  ':з ': 'AI',
  ':$ ': 'ERT',
  '#$ ': 'ERT',
  '.$ ': 'ERT',
  ':- ': 'SpecOps',
  '#- ': 'SpecOps',
  '.- ': 'SpecOps',
  ':_ ': 'SyndTeam',
  '#_ ': 'SyndTeam',
  '._ ': 'SyndTeam',
  ':+ ': 'Special',
  '#+ ': 'Special',
  '.+ ': 'Special',
  ':b ': 'Binary',
  '#b ': 'Binary',
  '.b ': 'Binary',
  '.и ': 'Binary',
  ':и ': 'Binary',
  '; ': 'Radio',
} as const;
